//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptv.XServer.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ptv.XServer.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting the country for Feature Layer routing failed. Please check your xServer connection..
        /// </summary>
        public static string ErrorCountryNotDetermined {
            get {
                return ResourceManager.GetString("ErrorCountryNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the xLocate server failed. Please check your network connection or the xLocate configuration..
        /// </summary>
        public static string ErrorGeocodeEndpointNotFound {
            get {
                return ResourceManager.GetString("ErrorGeocodeEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a destination..
        /// </summary>
        public static string ErrorNoDestWayPoint {
            get {
                return ResourceManager.GetString("ErrorNoDestWayPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the Feature Layers failed. Please check your xServer connection..
        /// </summary>
        public static string ErrorNoFeatureLayerFound {
            get {
                return ResourceManager.GetString("ErrorNoFeatureLayerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a start and destination..
        /// </summary>
        public static string ErrorNoWaypointsSet {
            get {
                return ResourceManager.GetString("ErrorNoWaypointsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route could not be calculated. Maybe a waypoint is too far away from a corresponding street. Please verify that in the range of 10 km streets are available for the specified waypoints..
        /// </summary>
        public static string ErrorRouteCalculationDefault {
            get {
                return ResourceManager.GetString("ErrorRouteCalculationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the xRoute server failed. Please check your network connection or the XRoute configuration..
        /// </summary>
        public static string ErrorRouteEndpointNotFound {
            get {
                return ResourceManager.GetString("ErrorRouteEndpointNotFound", resourceCulture);
            }
        }
    }
}
