//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomLocalizer
{
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ptv.XServer.Controls.Map.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aerials ähnelt.
        /// </summary>
        public static string Aerials {
            get {
                return ResourceManager.GetString("Aerials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background ähnelt.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layers ähnelt.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E ähnelt.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labels ähnelt.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N ähnelt.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selectability ähnelt.
        /// </summary>
        public static string Selectability {
            get {
                return ResourceManager.GetString("Selectability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S ähnelt.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absolute speed: {0} km/h ähnelt.
        /// </summary>
        public static string ToolTipTrafficIncidentsAbsoluteSpeed {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsAbsoluteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay: {0} min ähnelt.
        /// </summary>
        public static string ToolTipTrafficIncidentsDelay {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length: {0:0.000} km ähnelt.
        /// </summary>
        public static string ToolTipTrafficIncidentsLength {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message: ähnelt.
        /// </summary>
        public static string ToolTipTrafficIncidentsMessage {
            get {
                return ResourceManager.GetString("ToolTipTrafficIncidentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not allowed for vehicles carrying combustibles. ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesCombustibles {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesCombustibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This restriction does not concern delivery vehicles. ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesFreeForDelivery {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesFreeForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not allowed for vehicles carrying hazardous goods. ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesHazardousGoods {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesHazardousGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not allowed for vehicles carrying goods hazardous to waters. ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesHazardousToWaters {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesHazardousToWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not allowed for vehicles of load type: {0}. ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesLoadType {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goods ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesLoadTypeGoods {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadTypeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mixed ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesLoadTypeMixed {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadTypeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passenger ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesLoadTypePassenger {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesLoadTypePassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal axle load: {0:###,###} kg ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesMaxAxleLoad {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxAxleLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal height: {0:0.00} m ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesMaxHeight {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal length: {0:0.00} m ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesMaxLength {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal weight: {0:###,###} kg ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesMaxWeight {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal width: {0:0.00} m ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesMaxWidth {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total permitted weight: {0:###,###} kg ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesTotalPermittedWeight {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesTotalPermittedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tunnel restriction code: {0} ähnelt.
        /// </summary>
        public static string ToolTipTruckAttributesTunnelRestriction {
            get {
                return ResourceManager.GetString("ToolTipTruckAttributesTunnelRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Truck attributes ähnelt.
        /// </summary>
        public static string TruckAttributes {
            get {
                return ResourceManager.GetString("TruckAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visibility ähnelt.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die W ähnelt.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
